# Generated by Django 3.1.2 on 2021-01-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='discordlogin.user')),
                ('local_timezone_offset', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('country_code', models.CharField(max_length=5, null=True)),
                ('country_name', models.CharField(max_length=20, null=True)),
                ('region_name', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('time_zone', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
