# Generated by Django 3.1.2 on 2021-01-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_geodata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geodata',
            options={'verbose_name': 'Users Geo', 'verbose_name_plural': 'Users Geo'},
        ),
        migrations.RenameField(
            model_name='geodata',
            old_name='id',
            new_name='user',
        ),
    ]
