# Generated by Django 3.1.2 on 2021-01-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0003_auto_20210115_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geodata',
            options={'verbose_name': 'User Geo Data', 'verbose_name_plural': 'Users Geo Data'},
        ),
    ]
