# Generated by Django 3.1.2 on 2020-11-08 04:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('position', models.IntegerField(null=True)),
                ('colour', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('discriminator', models.CharField(max_length=4)),
                ('avatar', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=32, null=True)),
                ('roles', models.ManyToManyField(to='cotlsite.Role')),
            ],
        ),
    ]
