# Generated by Django 3.1.2 on 2020-11-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0002_member_user_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-position']},
        ),
    ]
