# Generated by Django 3.1.2 on 2020-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0003_auto_20201108_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nation_id',
            field=models.IntegerField(null=True),
        ),
    ]
