# Generated by Django 3.1.2 on 2020-11-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0005_auto_20201120_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='discriminator',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pnwdata',
            name='discord_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotlsite.member'),
        ),
    ]
