# Generated by Django 3.1.2 on 2020-11-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0006_auto_20201121_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_model',
        ),
    ]
