# Generated by Django 3.1.2 on 2020-12-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0007_remove_member_user_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnwdata',
            options={'verbose_name': 'PnW Data', 'verbose_name_plural': 'PnW Profiles'},
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
