# Generated by Django 3.1.2 on 2020-12-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0008_auto_20201216_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PnWData',
            new_name='MemberNation',
        ),
        migrations.AlterModelOptions(
            name='membernation',
            options={'verbose_name': 'Member Nation', 'verbose_name_plural': 'Member Nations'},
        ),
    ]
