# Generated by Django 3.1.2 on 2020-12-22 20:55

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cotlsite', '0009_auto_20201217_1359'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
        migrations.AddField(
            model_name='role',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
