# Generated by Django 3.1.2 on 2020-12-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0009_auto_20201217_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
