# Generated by Django 3.1.2 on 2020-12-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0010_auto_20201222_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
    ]
