# Generated by Django 3.1.2 on 2021-02-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotlsite', '0012_auto_20210225_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernation',
            name='discord_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotlsite.member'),
        ),
    ]
