# Generated by Django 3.1.2 on 2020-12-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('alliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('alliance_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceTEST',
            fields=[
                ('alliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('alliance_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nation_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NationTEST',
            fields=[
                ('nation_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMemberTEST',
            fields=[
                ('nation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pnwdata.nation')),
                ('alliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pnwdata.alliance')),
                ('money', models.IntegerField()),
            ],
            bases=('pnwdata.alliance', 'pnwdata.nation'),
        ),
        migrations.CreateModel(
            name='AllianceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.alliance')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.nation')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMemberTEST2',
            fields=[
                ('nation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pnwdata.nation')),
                ('money', models.IntegerField()),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.alliance')),
            ],
            bases=('pnwdata.nation',),
        ),
    ]
