# Generated by Django 3.1.2 on 2021-01-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pay_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_datetime', models.DateTimeField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.alliancemember')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activity',
            },
        ),
    ]
