# Generated by Django 3.1.2 on 2020-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0002_auto_20201222_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancemember',
            name='aluminum',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='bauxite',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='coal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='food',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='gasoline',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='iron',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='lead',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='money',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='munitions',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='oil',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='steel',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alliancemember',
            name='uranium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='aluminum',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bauxite',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='coal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='food',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='gasoline',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='iron',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='lead',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='money',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='munitions',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='oil',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='steel',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='uranium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='aluminum',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bauxite',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='coal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='food',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='gasoline',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='iron',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='lead',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='money',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='munitions',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='oil',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='steel',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='uranium',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='aluminum',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bauxite',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='coal',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='food',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='gasoline',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='iron',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='lead',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='money',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='munitions',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='oil',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='steel',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='uranium',
            field=models.FloatField(default=0, null=True),
        ),
    ]
