# Generated by Django 3.1.2 on 2021-02-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0002_auto_20210124_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alliancemember',
            options={'ordering': ['nation__nationid']},
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('date', models.DateField()),
                ('node', models.CharField(max_length=30)),
                ('tax_id', models.IntegerField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.nation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='taxrecord',
            constraint=models.UniqueConstraint(fields=('nation', 'date'), name='unique_tax_record'),
        ),
    ]
