# Generated by Django 3.1.2 on 2020-12-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0003_auto_20201222_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('nation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pnwdata.nation')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'holdings',
                'verbose_name_plural': 'holdings',
            },
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
