# Generated by Django 3.1.2 on 2021-02-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0003_auto_20210212_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxrecord',
            old_name='node',
            new_name='note',
        ),
    ]
