# Generated by Django 3.1.2 on 2021-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0004_auto_20210212_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
