# Generated by Django 3.1.2 on 2020-12-23 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0004_auto_20201222_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('tx_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('withdrew_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('deposited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
