# Generated by Django 3.1.2 on 2021-02-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0005_auto_20210212_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('snapshot_datetime', models.DateField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
