# Generated by Django 3.1.2 on 2020-12-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0005_deposit_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='id',
            new_name='tx_id',
        ),
    ]
