# Generated by Django 3.1.2 on 2021-02-17 22:11

from django.db import migrations, models
import django.db.models.deletion


# noinspection DuplicatedCode
class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0006_bankrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('resource', models.CharField(choices=[('money', 'Money'), ('food', 'Food'), ('coal', 'Coal'), ('oil', 'Oil'), ('uranium', 'Uranium'), ('bauxite', 'Bauxite'), ('iron', 'Iron'), ('gasoline', 'Gasoline'), ('munitions', 'Munitions'), ('aluminum', 'Aluminum'), ('steel', 'Steel'), ('credits', 'Credits')], max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='bankrecord',
            old_name='snapshot_datetime',
            new_name='snapshot_date',
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('offer_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('accepter_nation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepter', to='pnwdata.nation')),
                ('offerer_nation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerer', to='pnwdata.nation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.market')),
            ],
        ),
    ]
