# Generated by Django 3.1.2 on 2021-01-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0006_auto_20201223_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='tx_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
