# Generated by Django 3.1.2 on 2021-02-18 00:10

from django.db import migrations, models
import django.db.models.deletion


# noinspection DuplicatedCode
class Migration(migrations.Migration):
    dependencies = [
        ('pnwdata', '0007_auto_20210217_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='resource',
            field=models.CharField(
                choices=[('food', 'Food'), ('coal', 'Coal'), ('oil', 'Oil'), ('uranium', 'Uranium'), ('bauxite', 'Bauxite'), ('iron', 'Iron'), ('gasoline', 'Gasoline'), ('munitions', 'Munitions'),
                         ('aluminum', 'Aluminum'), ('steel', 'Steel'), ('credits', 'Credits')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='pnwdata.market'),
        ),
    ]
