# Generated by Django 3.1.2 on 2021-01-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0007_auto_20210112_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='tx_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
