# Generated by Django 3.1.2 on 2021-01-13 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0008_auto_20210112_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('request_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_type', models.CharField(choices=[('AID', 'Aid Request'), ('WITHDRAW', 'Withdraw Request'), ('LOAN', 'Loan Request')], max_length=20)),
                ('status', models.CharField(choices=[('Y', 'ACCEPTED'), ('N', 'DECLINED'), (None, 'PROCESSING')], default=None, max_length=20, null=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
