# Generated by Django 3.1.2 on 2021-02-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0008_auto_20210217_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='accepter_nation_id',
            new_name='accepter_nation',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='offerer_nation_id',
            new_name='offerer_nation',
        ),
    ]
