# Generated by Django 3.1.2 on 2021-02-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0009_auto_20210217_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='resource',
            new_name='market',
        ),
    ]
