# Generated by Django 3.1.2 on 2021-02-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0010_auto_20210217_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-trade_id']},
        ),
    ]
