# Generated by Django 3.1.2 on 2021-01-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0010_auto_20210113_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
