# Generated by Django 3.1.2 on 2021-02-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0011_auto_20210217_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='resource',
            field=models.CharField(choices=[('food', 'Food'), ('coal', 'Coal'), ('oil', 'Oil'), ('uranium', 'Uranium'), ('bauxite', 'Bauxite'), ('iron', 'Iron'), ('lead', 'Lead'), ('gasoline', 'Gasoline'), ('munitions', 'Munitions'), ('aluminum', 'Aluminum'), ('steel', 'Steel'), ('credits', 'Credits')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
