# Generated by Django 3.1.2 on 2021-02-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0013_auto_20210218_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, null=True)),
                ('food', models.FloatField(default=0, null=True)),
                ('coal', models.FloatField(default=0, null=True)),
                ('oil', models.FloatField(default=0, null=True)),
                ('uranium', models.FloatField(default=0, null=True)),
                ('bauxite', models.FloatField(default=0, null=True)),
                ('iron', models.FloatField(default=0, null=True)),
                ('lead', models.FloatField(default=0, null=True)),
                ('gasoline', models.FloatField(default=0, null=True)),
                ('munitions', models.FloatField(default=0, null=True)),
                ('aluminum', models.FloatField(default=0, null=True)),
                ('steel', models.FloatField(default=0, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('message_id', models.BigIntegerField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdata.nation')),
            ],
            options={
                'verbose_name': 'Aid Request',
                'verbose_name_plural': 'Aid Requests',
            },
        ),
    ]
