# Generated by Django 3.1.2 on 2021-02-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0014_auto_20210227_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aid',
            options={'verbose_name': 'aid', 'verbose_name_plural': 'aid'},
        ),
        migrations.RenameField(
            model_name='aid',
            old_name='request_date',
            new_name='sent_on',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='message_id',
            new_name='identifier',
        ),
        migrations.AlterField(
            model_name='aid',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
