# Generated by Django 3.1.2 on 2021-03-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0015_auto_20210227_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('mmr', models.CharField(max_length=4)),
                ('wc_money', models.IntegerField()),
                ('wc_food', models.IntegerField()),
                ('wc_uranium', models.IntegerField()),
                ('wc_gasoline', models.IntegerField()),
                ('wc_munitions', models.IntegerField()),
                ('wc_steel', models.IntegerField()),
                ('wc_aluminum', models.IntegerField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
