# Generated by Django 3.1.2 on 2021-03-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0016_allianceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allianceconfig',
            name='enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
