# Generated by Django 3.1.2 on 2021-03-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0017_auto_20210301_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allianceconfig',
            name='mmr',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_aluminum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_gasoline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_munitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_steel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allianceconfig',
            name='wc_uranium',
            field=models.IntegerField(default=0),
        ),
    ]
