# Generated by Django 3.1.2 on 2021-07-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0018_auto_20210301_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alliancemember',
            old_name='cityprojecttimerturns',
            new_name='turns_since_last_city',
        ),
        migrations.AddField(
            model_name='alliancemember',
            name='turns_since_last_project',
            field=models.IntegerField(null=True),
        ),
    ]
