# Generated by Django 3.1.2 on 2021-07-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdata', '0020_remove_alliancemember_turns_since_last_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancemember',
            name='turns_since_last_city',
            field=models.IntegerField(null=True),
        ),
    ]
